Add preflight check

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,13 +1,11 @@
 #
 # This configuration requires a few environment variables to be configured in circleci:
 # GCP_AUTH - The base64 encoded content of a GCP json key with the following permissions:
-#   *
-#   *
 # GCP_PROJECT - The id of the GCP project
 # CLUSTER_NAME - Name of the kubernetes cluster
 # CLUSTER_REGION - Name of the kubernetes cluster region
 # PROJECT_NAME - Name of the project, used for containers & k8s.
-#
+
 # defaults shared between all jobs
 defaults: &defaults
   working_directory: /app
@@ -26,6 +24,25 @@ authenticate: &authenticate
 
 version: 2
 jobs:
+  preflight:
+    docker:
+      - image: busybox
+    steps:
+      - run:
+          name: Preflight Check
+          command: |
+            required_vars=(GCP_AUTH GCP_PROJECT CLUSTER_NAME CLUSTER_REGION PROJECT_NAME)
+			      missing_vars=()
+            for i in "${required_vars[@]}"
+            do
+                test -n "${!i:+y}" || missing_vars+=("$i")
+            done
+            if [ ${#missing_vars[@]} -ne 0 ]
+            then
+                echo "The following variables are not set, but should be:" >&2
+                printf ' %q\n' "${missing_vars[@]}" >&2
+                exit 1
+      			fi
   run_tests:
     <<: *defaults
     docker:
@@ -69,7 +86,7 @@ jobs:
           command: |
             make test
       # Static files are by default collected into the "static" folder. If configuration change
-      # is required, the STATIC_ROOT? django setting must also be updated in the persitance step
+      # is required, the STATIC_ROOT django setting must also be updated in the persitance step
       # which follows the static collection step.
       - run:
           name: Collect static
@@ -117,17 +134,10 @@ jobs:
       - run:
           <<: *authenticate
       - run:
-          name: Generate Kubernetes Deployments
-          command: |
-            mkdir k8s-deploy
-            for filename in ./k8s/*.template; do
-                cat "$filename" |python ./scripts/override-project-info > k8s-deploy/$(basename "$filename" .template).yaml
-            done
-      - run:
           name: Update deployment
           command: |
             gcloud container clusters get-credentials --region="${CLUSTER_REGION}" ${CLUSTER_NAME}
-            kubectl apply -f ./k8s-deploy
+            kubectl apply -f ./k8s
             kubectl set image deployment ${PROJECT_NAME} ${PROJECT_NAME}=gcr.io/${GCP_PROJECT}/${PROJECT_NAME}:$CIRCLE_SHA1
             kubectl set image deployment ${PROJECT_NAME}-worker ${PROJECT_NAME}-worker=gcr.io/${GCP_PROJECT}/${PROJECT_NAME}:$CIRCLE_SHA1
 
@@ -135,7 +145,14 @@ workflows:
   version: 2
   test-deploy:
     jobs:
-      - run_tests
+      - preflight
+	  - run_tests:
+          requires:
+            - preflight
+          filters:
+            branches:
+              only:
+                - master
       - image:
           requires:
             - run_tests
